### PR TITLE
fix apply button width for mobile. close #115

### LINKED ISSUE #115: smaller apply button on col-m
screen shot 2016-08-06 at 3 20 28 pm

### PR DESCRIPTION
**Pull request by mikeyrayvon**

### CODE REVIEW

File: partials/archive-exhibitor/apply.php [hunk 1]
```diff
@@ -13,7 +13,7 @@
       if (!empty($exhibitors_apply_heading)) {
     ?>
       <div class="row">
-        <div class="col col-s col-s-12 text-align-center">
+        <div class="col col-s col-s-12 col-m col-m-12 col-l col-l-12 text-align-center">
```
Comment (varffs) [inline partials/archive-exhibitor/apply.php:16]: why would these extra classes be needed?

Comment (mikeyrayvon) [inline partials/archive-exhibitor/apply.php:16]: because the gutter changes, but when the gutter changes it also resets the flex property. there are some flaws in the boilerplate to be sure

Comment (varffs) [inline partials/archive-exhibitor/apply.php:16]: so the 12 col classes dont do anything. they override a value of 100% with a new value of 100%. but the `col-m` and `col-l` classes change the gutter width. why not just override the gutter values for `.col` to save every column needing 4 `col` declarations?
